import { TOKEN_NAMES } from "~/themes/tokens";
import type { ThemeDefinition } from "~/types/theme";

/**
 * `color-scheme` rides along with the colours because native UI — form
 * controls, the CodeMirror search field, scrollbars — takes its cue from it
 * and would otherwise follow the operating system instead of the theme.
 */
export const tokenDeclarations = (theme: ThemeDefinition): string =>
  [
    `color-scheme: ${theme.appearance};`,
    ...TOKEN_NAMES.map((name) => `--${name}: ${theme.tokens[name]};`),
    `--shadow-panel: ${theme.shadows.panel};`,
  ].join("\n  ");

export const tokenBlock = (theme: ThemeDefinition, selector: string): string =>
  `${selector} {\n  ${tokenDeclarations(theme)}\n}`;

/**
 * The stylesheet loaded by the app. Every theme is present at all times and
 * `data-theme` on the root element picks one, so switching costs no network
 * request and the boot script can choose before the first paint.
 */
export const themesStylesheet = (themes: ThemeDefinition[]): string =>
  [
    "/* Generated by scripts/generate-theme-css.ts — do not edit.",
    "   Edit themes/definitions/*.ts and run `npm run themes:build`. */",
    "",
    ...themes.map((theme) => tokenBlock(theme, `[data-theme="${theme.id}"]`)),
    "",
  ].join("\n");
